version: '3'

services:
  create-env:
    image: bash
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "echo 'DB_HOST=localhost
      DB_PORT=5432
      DB_USER=daddy
      DB_PASSWORD=bestvater
      DB_NAME=partyPollDB' > .env"

  frontend:
    container_name: partypoll_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - create-env

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: partyPollDB
      POSTGRES_USER: daddy
      POSTGRES_PASSWORD: bestvater
    volumes:
      - ./data:/var/lib/postgresql/data
    depends_on:
      - create-env

  backend:
    container_name: partypoll_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
      - create-env
    environment:
      - DB_HOST=db
      - DB_USER=daddy
      - DB_PASSWORD=bestvater
      - DB_NAME=partyPollDB