definitions:
  models.GenericPollResponse:
    type: object
  models.PollInfo:
    properties:
      description:
        type: string
      id:
        type: string
      pollType:
        type: string
      title:
        type: string
    type: object
  server.QRRequest:
    properties:
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      responses: {}
      summary: Login an existing user
      tags:
      - Auth
  /polls:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PollInfo'
            type: array
      summary: Get all polls w/o results
      tags:
      - Polls
    post:
      parameters:
      - description: Add Poll
        in: body
        name: poll
        required: true
        schema:
          $ref: '#/definitions/models.PollInfo'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PollInfo'
            type: array
      summary: Post a poll
      tags:
      - Polls
  /polls/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Poll ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Delete a poll
      tags:
      - Polls
    get:
      parameters:
      - description: Poll ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get a poll and it's results
      tags:
      - Polls
    post:
      parameters:
      - description: Poll ID
        in: path
        name: id
        required: true
        type: string
      - description: Add poll response
        in: body
        name: poll
        required: true
        schema:
          $ref: '#/definitions/models.GenericPollResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Post a poll result
      tags:
      - Polls
  /qr:
    post:
      consumes:
      - application/json
      description: Generate a QR code from the provided URL
      parameters:
      - description: QR request
        in: body
        name: qrRequest
        required: true
        schema:
          $ref: '#/definitions/server.QRRequest'
      produces:
      - image/png
      responses:
        "200":
          description: QR code image
          schema:
            type: file
        "400":
          description: Invalid request format
          schema:
            type: string
        "500":
          description: Failed to generate QR code
          schema:
            type: string
      summary: Generate QR code
      tags:
      - QR
  /refresh-token:
    post:
      responses: {}
      summary: Create a refresh token
      tags:
      - Auth
swagger: "2.0"
